import os
import time
# time.sleep(3600)
# os.system("python ./SOC_40.py 1>>SOC_40_log.txt")
# os.system("python ./SOC_50.py 1>>SOC_50_log.txt")
# os.system("python ./EOC_D.py 1>>EOC_D_log.txt")
# os.system("python ./EOC_A.py 1>>EOC_A_log.txt")
# os.system("python ./EOC_S.py 1>>EOC_S_log.txt")
# os.system("python ./EOC_B.py 1>>EOC_B_log.txt")
# os.system("python ./EOC_P.py 1>>EOC_P_log.txt")
# os.system("python ./SOC_50_2.py 1>>SOC_50_2_log.txt")
# os.system("python ./SOC_50_6.py 1>>SOC_50_6_log.txt")
# os.system("python ./SOC_50_8.py 1>>SOC_50_8_log.txt")
# os.system("python ./SOC_50_4.py 1>>SOC_50_4_log.txt")
os.system("python ./SOC_50_1.py 1>>SOC_50_1_log.txt")
os.system("python ./SOC_50_05.py 1>>SOC_50_05_log.txt")